language: python
python:
    - "3.7"
script:
    - coverage run --branch -m unittest discover
before_install:
    - pip install coverage
    - pip install codecov
    - pip install -r requirements.txt
after_success:
    - codecov
